#!/usr/bin/env bash
# kitty +icat --clear --silent --transfer-mode file
# kitty +kitten icat --clear --transfer-mode file < /dev/null > /dev/tty
kitty +kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty
