theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
auto-save = true
rulers = [100]
cursorline = true
# cursorcolumn = true
# bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
# wrap-indicator = "↩ "

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true
character = "│" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner", "diagnostics"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["file-encoding", "selections", "register", "position", "position-percentage", "total-line-numbers"]
# left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
# center = []
# right = ["diagnostics", "selections", "register", "position", "file-encoding"]
# separator = "│"
# mode.normal = "NOR"
# mode.insert = "INS"
# mode.select = "SEL"

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true
