# export PATH="$HOME/.local/share/knvim/mason/bin:$PATH"

# ─────────────────────────────────────────────────────────────────────────────────────────────────
[[language]]
name = "python"
# formatter = { command = "black", args = ["--quiet", "-"] }
formatter = { command = "ruff" }
auto-format = false
roots = ["pyproject.toml"]
language-servers = ["pyright"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

# ─────────────────────────────────────────────────────────────────────────────────────────────────
[[language]]
name = "bash"
formatter = { command = "shfmt" }

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]
config = {}

# ─────────────────────────────────────────────────────────────────────────────────────────────────
[language-server.marksman]
command = "marksman"
args = ["server"]
config = {}
