[manager]
prepend_keymap = [
    { on = [ "T" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview" },
    { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
    { on = "H", run = "plugin duckdb -1", desc = "Scroll one column to the left" },
    { on = "L" ,run = "plugin duckdb +1", desc = "Scroll one column to the right" },
    { on = ["g", "o"], run = "plugin duckdb -open", desc = "open with duckdb" },
    { on = ["g", "u"], run = "plugin duckdb -ui", desc = "open with duckdb ui" },
]

append_keymap = [
    { on = [ "m", "h" ], run = "linemode size_and_mtime", desc = "Linemode: size and mtime" },
]

[input]
prepend_keymap = [
    { on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
]
