[manager]
prepend_keymap = [
    { on = [ "T" ], run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
    { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
    { on = [ "c", "a" ], run = "plugin compress", desc = "Archive selected files" },
]

append_keymap = [
    { on = [ "m", "h" ], run = "linemode size_and_mtime", desc = "Set linemode to size and mtime" },
]

[input]
prepend_keymap = [
    { on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
]
