[flavor]
use = "catppuccin-macchiato"

[icon]
prepend_dirs = [
    { name = ".Trash", text = "" },
    { name = ".vscode", text = "󰨞" },
    { name = "Amazon WorkDocs Drive", text = "" },
    { name = "AmazonWorkDocsCompanion", text = "" },
    { name = "Applications", text = "" },
    { name = "datasets", text = "" },
    { name = "workspaces", text = "" },
]
