[mgr]
# linemode = "mtime"
linemode = "size_and_mtime"
# ratio = [1, 2, 5]
show_hidden = true

[preview]
max_width = 2048
max_height = 2048

[opener]
pdf = [
    { run = 'zathura "$@"', block = false, desc = "Zathura" },
]

[open]
append_rules = [
    { mime = "application/pdf", use = [ "open", "pdf", "reveal" ] },
]

