#!/usr/bin/env bash
# =============================================================================
# BSPWM config
# =============================================================================
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Configure both monitors at the same time
desktop_config() {
    #bspc config $1 $2
    for monitor in $(bspc query -M); do
        bspc config -m "$monitor" "$1" "$2"
    done
}

desktop_config border_width         2
desktop_config window_gap          10

# desktop_config focused_border_color \#61afef
# desktop_config active_border_color  \#98c379
desktop_config focused_border_color \#8AADF4
desktop_config active_border_color  \#A6DA95

desktop_config split_ratio                 0.5
desktop_config borderless_monocle          true
desktop_config gapless_monocle             true
desktop_config focus_follows_pointer       true
desktop_config history_aware_focus         true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# =============================================================================
# Startup programs
# =============================================================================
# polybar
"$HOME/.config/polybar/launch_bspwm.sh" &

# Simple X hotkey deamon
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/sxhkdrc_bspwm" &

# Monitor settings
"$HOME/.screenlayout/default.sh" &

# Wallpaper settings
nitrogen --restore &

# Compositor
picom --experimental-backends &
touch /tmp/picom &

# Autolock the screen
xautolock -time 30 -corners 000- -locker "$HOME/.config/i3/scripts/i3lock.sh" &

# Lockscreen settings
xss-lock --transfer-sleep-lock -- "$HOME/.config/i3/scripts/transfer-sleep-lock-generic-delay.sh" &

# Change default cursor
xsetroot -cursor_name left_ptr &

# Network manager
nm-applet &

# Bluetooth manager
blueberry-tray &

# Ibus
ibus-daemon -drx &

# Dropbox
# sleep 10; dropbox start &

# Power manager
xfce4-power-manager &

# Clipboard manager
xfce4-clipman &

# Package manager
pamac-tray &

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }


# =============================================================================
# Windows rules
# =============================================================================
bspc rule -a '*:pavucontrol' state=floating
bspc rule -a '*:matplotlib' state=floating
bspc rule -a '*:com.gitlab.bitseater.meteo' state=floating
bspc rule -a '*:meteo' state=floating
bspc rule -a '*:xfce4-taskmanager' state=floating
bspc rule -a 'Galculator' state=floating
bspc rule -a 'Zathura' state=tiled
